server:
  port: 9000
spring:
  config:
    import: "optional:configserver:"
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: http://localhost:8080/
          predicates:
            - Path=/products/**
        - id: customer-service
          uri: http://localhost:8081/
          predicates:
            - Path=/customers/**